# Hacker Theme
remote_theme: pages-themes/hacker@v0.2.0
plugins:
- jekyll-remote-theme

title: 'SMU CRCP 6310 - Spring 2025'
description: Student project submissions from CRCP 6310 - Introduction to Creative Coding; Spring 2025 term.
show_downloads: false
